function __jj.init
    abbr jst        'jj status'
    abbr jsh        'jj show'
    abbr jshs       'jj show --summary'
    abbr jl         'jj log'
    abbr jb         'jj bookmark'
    abbr jbc        'jj bookmark create'
    abbr jbd        'jj bookmark delete'
    abbr jbm        'jj bookmark move'
    abbr jbm@       'jj bookmark move --to @'
    abbr jcl        'jj git clone --colocate'
    abbr jclo       'jj git clone --colocate --remote upstream'
    abbr jd         'jj desc'
    abbr jdm        'jj desc -m'
    abbr jdf        'jj diff'
    abbr jdg        'jj diff --git'
    abbr je         'jj edit'
    abbr jfa        'jj git fetch --all-remotes'
    abbr jf         'jj git fetch'
    abbr jp         'jj git push'
    abbr jpa        'jj git push --all'
    abbr jpb        'jj git push --bookmark'
    abbr jpc        'jj git push --change'
    abbr jpd        'jj git push --deleted'
    abbr jn         'jj new'
    abbr jna        'jj new -A'
    abbr jnb        'jj new -B'
    abbr jnn        'jj new --no-edit'
    abbr jnna       'jj new --no-edit -A'
    abbr jnnb       'jj new --no-edit -B'
    abbr jsq        'jj squash'
    abbr jgr        'jj git remote'
    abbr jgra       'jj git remote add'
    abbr jgrl       'jj git remote list'
    abbr jrb        'jj rebase'
    abbr jrbr       'jj rebase -r'
    abbr jrbs       'jj rebase -s'
    abbr ja         'jj abandon'
end
